# Welcome to Jekyll!
# Site Settings
locale                   : "en"
title                    : "timjones.io"
title_separator          : "-"
name                     : "Tim Jones"
description              : "Blog and open source projects by Tim Jones."
url                      : "http://timjones.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
#theme                    : minimal-mistakes-jekyll
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : disqus
  disqus:
    shortname            : timjones
atom_feed:
  path                   : # blank (default) uses feed.xml

# Social Sharing
twitter:
  username               : _tim_jones_
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/_tim_jones_"

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-5166698-5"


# Site Author
author:
  name             : "Tim Jones"
  avatar           : "/assets/images/bio-photo.png"
  bio              : "Compilers, 3D graphics, Visual Studio extensibility."
  email            : tim@timjones.io
  github           : tgjones
  twitter          : _tim_jones_


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: "blog/archive/:categories/:year/:month/:day/:title"
timezone: "UTC" # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-responsive-image
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-archives
  - jemoji

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # [all]
  - scope:
      path: ""
    values:
      layout: master
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: project

responsive_image:
  template: _includes/responsive-image.html

  sizes:
    - width: 400
    - width: 800
    - width: 1200
    - width: 1600

jekyll-archives:
  enabled:
    - tags
  layout: 'archive'
  permalinks:
    tag: '/blog/tags/:name/'